### ISSUE TITLE
Hello, World doesn't explain where ProgramResult and Success come from.

### ISSUE THREAD

**Issue by dreid** [alex/bagel#24]
https://github.com/alex/bagel/blob/master/samples/hello-world.bagel

Presumably `ProgramResult` needs to be imported from somewhere and is enum so `return Success` should be `return ProgramResult.Success` ?

**Comment by alex** [comment]
Thus far I've been assuming ProgramResult was a builtin. I'm not 100% sure how I feel about that, what do you think?

**Comment by dreid** [comment]
I'm -1 on magic names from nowhere.

**Comment by alex** [comment]
Having some builtin names, like `ProgramResult` isn't a magic name from
nowhere anymore than `Int` is.

On Sun, Jul 6, 2014 at 4:56 PM, David Reid notifications@github.com wrote:

> I'm -1 on magic names from nowhere.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/alex/bagel/issues/24#issuecomment-48130954.

## 

"I disapprove of what you say, but I will defend to the death your right to
say it." -- Evelyn Beatrice Hall (summarizing Voltaire)
"The people's good is the highest law." -- Cicero
GPG Key fingerprint: 125F 5C67 DFE9 4084

**Comment by alex** [comment]
#25 improves this a bit, can you take a look at that?
