### ISSUE TITLE
Decide on linkage model

### ISSUE THREAD

**Issue by alex** [alex/bagel#3]
Static, dynamic, users' choice?

**Comment by dstufft** [comment]
Static makes deployment easier, and it seems to be working well for Go, but it does make it harder to use LGPL licensed things in a proprietary application (https://www.gnu.org/licenses/gpl-faq.html#LGPLStaticVsDynamic).

**Comment by alex** [comment]
There's also the security concern: you can't just have your OS upgrade one package and then restart the processes, everything needs to be rebuilt.

**Comment by dstufft** [comment]
That's not actually that big of a deal with tooling IMO. The biggest drawback there is tooling isn't currently super great at this case and the extra bandwidth used and churn from pulling down a bunch of different packages instead of just one.

**Comment by alex** [comment]
I don't care much about churn or bandwidth, just whether it exposes users to security issues. If you don't think it exposes security risk, I think I'm fine just saying "allways static", it really is a better UX>

**Comment by dstufft** [comment]
Well to be specific, with the proper tooling it doesn't. I'd expect the language specific tooling to handle it perfectly fine, the main thing I'd be worried about is generic tooling. We don't have "static linking" in Python, but the recommend best practice is to pin to exact versions (which is about as close to static linking as Python gets). The places where dynamic linking is more helpful are more like Linux distros where you don't typically pin to a version of a package and you're basically always tracking whatever the latest in the repository is. I expect application deployments of anything using Bagel to require a manual (where manual might mean run some command that does it for you) step to upgrade packages so it shouldn't be a big deal to use static in that scenario.

**Comment by dstufft** [comment]
One thing I just thought of. I'm not actually sure if the answer. If I have a library, it has dependencies which are statically compiled into it. Can I distribute the artifact (the .a basically iirc) and a downstream project statically links against that artifact?

Essentially are binary packages still a thing? (Just build dependencies instead of runtime).

**Comment by alex** [comment]
I think for now, let's assume no, binary packages aren't a thing.

On Tue, Mar 11, 2014 at 1:16 PM, Donald Stufft notifications@github.comwrote:

> One thing I just thought of. I'm not actually sure if the answer. If I
> have a library, it has dependencies which are statically compiled into it.
> Can I distribute the artifact (the .a basically iirc) and a downstream
> project statically links against that artifact?
> 
> Essentially are binary packages still a thing? (Just build dependencies
> instead of runtime).
> 
> > On Mar 11, 2014, at 4:09 PM, Alex Gaynor notifications@github.com
> > wrote:
> > 
> > Closed #3 via c422f04.
> > 
> > —
> > Reply to this email directly or view it on GitHub.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/alex/bagel/issues/3#issuecomment-37344299
> .

## 

"I disapprove of what you say, but I will defend to the death your right to
say it." -- Evelyn Beatrice Hall (summarizing Voltaire)
"The people's good is the highest law." -- Cicero
GPG Key fingerprint: 125F 5C67 DFE9 4084

**Comment by dstufft** [comment]
Ok cool, that makes the package installer more or less a build tool and makes it so the PyPI of Bagel (The Deli? The Bagelshop?) can remain more or less a specialized object store without much in the way smarts.

**Comment by alex** [comment]
You mean we can just scrape random websites!?!!!!!111?!??

On Tue, Mar 11, 2014 at 1:25 PM, Donald Stufft notifications@github.comwrote:

> Ok cool, that makes the package installer more or less a build tool and
> makes it so the PyPI of Bagel (The Deli? The Bagelshop?) can remain more or
> less a specialized object store without much in the way smarts.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/alex/bagel/issues/3#issuecomment-37345300
> .

## 

"I disapprove of what you say, but I will defend to the death your right to
say it." -- Evelyn Beatrice Hall (summarizing Voltaire)
"The people's good is the highest law." -- Cicero
GPG Key fingerprint: 125F 5C67 DFE9 4084

**Comment by dstufft** [comment]
Scraping random websites is how all the best tools work.
