### ISSUE TITLE
pronunciation guide

### ISSUE THREAD

**Issue by glyph** [alex/bagel#52]
It's hard to speak programming languages aloud.  Mathematics, however, has fairly standard pronunciations of various symbols.  Bagel should include a guide to pronouncing its syntactic constructs (including, if possible, indentation).

**Comment by alex** [comment]
I agree with this idea, but I'm going to close this for now, as we can't act on it. This should become a component of hte glossary once the syntax is more fleshed out, and introduced as a part of writing the language tutorial.

**Comment by alex** [comment]
Thanks for suggesting this though, it's a great idea.
