### ISSUE TITLE
consider a different keyword than "match" for pattern matching

### ISSUE THREAD

**Issue by glyph** [alex/bagel#54]
"match" certainly evokes "pattern matching" if one is evaluating a language based on prior art, but the fact remains that the syntax reads oddly because one does not match things "as" things, so it sounds slightly nonsensical when read.  (Again, considering #53).

Some alternate suggestions to consider:

"when"

```
    when system:
        is MeasuringSystem.Imperial:
            return "Feet"
        is MeasuringSystem.Metric:
            return "Meters"
```

"matches"

```
    when system:
        matches MeasuringSystem.Imperial:
            return "Feet"
        matches MeasuringSystem.Metric:
            return "Meters"
```

"to"

```
    match system:
        to MeasuringSystem.Imperial:
            return "Feet"
        to MeasuringSystem.Metric:
            return "Meters"
```

"with"

```
    match system:
        with MeasuringSystem.Imperial:
            return "Feet"
        with MeasuringSystem.Metric:
            return "Meters"
```

"is:"

(Bonus: no new keywords! That may be a negative point though, since it may seriously mess with new programmers' understanding of what "if" is doing)

```
    if system is:
        MeasuringSystem.Imperial:
            return "Feet"
        MeasuringSystem.Metric:
            return "Meters"
```

"?" (pose the match as a question, the clauses are the answer)

```
    is system:
        MeasuringSystem.Imperial?
            return "Feet"
        MeasuringSystem.Metric?
            return "Meters"
```

**Comment by alex** [comment]
All these examples use the enum-as-constant form. Can you try evaluating these in the context of using match for extraction as well?

(PS: I'm not going to overload the if statement)

**Comment by dstufft** [comment]
I like

```
    when system:
        matches MeasuringSystem.Imperial:
            return "Feet"
        matches MeasuringSystem.Metric:
            return "Meters"
```

**Comment by alex** [comment]
Do you feel that reading works for the exaction use case? Consistency with
the extraction use case was how I came up with "match ... as..." in the
first place.

On Mon, Oct 20, 2014 at 11:44 AM, Donald Stufft notifications@github.com
wrote:

> I like
> 
> ```
> when system:
>     matches MeasuringSystem.Imperial:
>         return "Feet"
>     matches MeasuringSystem.Metric:
>         return "Meters"
> ```
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/alex/bagel/issues/54#issuecomment-59818857.

## 

"I disapprove of what you say, but I will defend to the death your right to
say it." -- Evelyn Beatrice Hall (summarizing Voltaire)
"The people's good is the highest law." -- Cicero
GPG Key fingerprint: 125F 5C67 DFE9 4084

**Comment by dstufft** [comment]
So...

```
    when d:
        matches Distance.Inches(x):
            return x
        matches Distance.Feet(x):
            return x * 12
```

I don't know that I like that, but I don't think I like

```
    match d:
        as Distance.Inches(x):
            return x
        as Distance.Feet(x):
            return x * 12
```

either. 

I'm not actually sure what `x` even is in that context. is it a Inches.. object? or is it the `UInt` that is contained inside of the enum? In either case, maybe...

```
    when d:
        matches Distance.Inches as x:
            return x
        matches Distance.Feet as x:
            return x * 12
```

**Comment by frewsxcv** [comment]
I would expect `matches Distance.Feet as x:` to result in `x` becoming the enum instead of the value contained within. Not to mention that enums can contain multiple values

**Comment by dstufft** [comment]
Well multiple values isn't difficult. `matches Distance.Feet as x, y` or `matches Distance.Feet as reason: x`.

The `x` is the enum not the value within thing is harder. The current syntax makes me feel like it's matching the return value of `Distance.Feet(x)` not unpacking the enum. Not sure which is worse.

**Comment by alex** [comment]
How about `match with`:

```
match system:
    with MeasuringSystem.Imperial:
       return 'feet'
    with MeasuringSystem.Metric:
        return 'quarts'
```

```
match distance:
    with Distance.Feet(n):
        return n * 12
    with Distance.Inches(n):
        return n
```

Do these both read ok?

**Comment by hynek** [comment]
1. -1 on having both `if` and `when`
2. I’m not sure whether `match…with` works for all use cases?

**Comment by nelhage** [comment]
Is there a reason we've dismissed "case" out of hand? That would be my default keyword to try for a pattern-matching construct.

**Comment by alex** [comment]
Meaning `match`/`case`? It's not obviously wrong, `case` is also being used
in `enum` definitions, which is either a nice parallel, or confusing term
reuse.

**Comment by danilolekovic** [comment]
:+1: for `with`. Very nice syntax!

**Comment by nelhage** [comment]
Maybe it's ruby warping my mind, but I'd have said `case`/`when`, or (ala
bash) `case`/`of`.
Meaning `match`/`case`? It's not obviously wrong, `case` is also being used
in `enum` definitions, which is either a nice parallel, or confusing term
reuse.
